#!/bin/bash

# 1st parameter: name of log file
# 2nd parameter: name of program
# 3rd parameter: name of input file
# 4th parameter: name of required output file

# the script checks if the output of a program
# is identical to it's desired output

./"$2" < "$3" > "$1"
difference=`diff "$1" "$4"`

if [ -z "$difference" ]; then 
	echo "Out files match"
	exit 0
else
	echo "Out files mismatch"
	exit 1
fi
