#!/bin/bash

valgrind --tool=memcheck ./$2 < "$3" 2> "$1" > /dev/null

er1=`cat "$1" | grep "ERROR SUMMARY: 0 errors from 0 contexts"`
er2=`cat "$1" | grep "LEAK SUMMARY:"`

if [[ "$er1"="$er2" && "$er2"="" ]]; then
	echo "Memeory test passed"
	exit 0
else
	echo "Memeory tets failed"
	exit 1
fi
