#!/bin/bash

# 1st parameter: list of tests

if [ -d "logFiles" ]; then
	echo "error!"
	exit 1
else
	mkdir "logFiles"
fi

NumOfLines=`wc -l "$1"`
num_line=0
num_success=0

while read -r line; do
	if [ -z "$line" ]; then
		continue
	fi
	
	(( num_line++ ))
	IFS='@'
	read -r -a split_line <<< "$line"
	description=${split_line[0]}
	program=${split_line[1]}
	input=${split_line[2]}
	req_output=${split_line[3]}
	
	echo "$num_line: $description"
	
	./testCompile logFiles/${num_line}.compile.log "$program" 2> /dev/null
	if [ $? -eq 0 ]; then
		(( num_success++ ))
	fi
	
	./testInOut logFiles/${num_line}.inout.log "$program" "$input" "$req_output" 2> /dev/null
	if [ $? -eq 0 ]; then
		(( num_success++ ))
	fi
	
	./testMem logFiles/${num_line}.memory.log "$program" "$input" 2> /dev/null
	if [ $? -eq 0 ]; then
		(( num_success++ ))
	fi
	
done < "$1"

echo "${num_success} tests passed out of $(( 3*$num_line ))"
	
exit 0	
	
	
	
	
	
